### ISSUE TITLE
Xcode Build Issue

### ISSUE THREAD

**Issue by rjallanreal** [plotfi/cxx-interop-test#2]
Hello,

I was unable to build with the Xcode 12.5 beta 3. The Swift compiler gives the following error: `'string_view' file not found`.

I have passed CPATH and SDKROOT as environment variables via 

`launchctl setenv SDKROOT /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`

and

`launchctl setenv CPATH /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/`.

Is there something I am missing to allow this to work in Xcode?

Also, Package.swift has the following line:

`cxxLanguageStandard: CXXLanguageStandard.cxx14`

which I find confusing, since it seems to me that string_view was added in C++17. Could you explain what the language standard does?

**Comment by rjallanreal** [comment]
Found the problem, in my case, CPATH was set incorrectly.

In my case, it should be set as follows:

`launchctl setenv CPATH /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1`

I can confirm that the example works in the current Xcode beta with a toolchain that I built from source yesterday.

**Comment by plotfi** [comment]
> Found the problem, in my case, CPATH was set incorrectly.
> 
> In my case, it should be set as follows:
> 
> `launchctl setenv CPATH /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1`
> 
> I can confirm that the example works in the current Xcode beta with a toolchain that I built from source yesterday.

Ah yes. I recently added a better readme to explain things better. Also tested things with latest swiftpm and showed how to build the latest swift+swiftpm to build this project.
